### ISSUE TITLE
problème de lien

### ISSUE THREAD

**Issue by colas31** [jeedom/documentation#12]
Hello,

Depuis cette page https://jeedom.github.io/documentation/plugins/jeelink/fr_FR/index.html#_changelog
Dans le paragraphe **6.2. Migration ancien mode Esclave** il y a un lien erroné. Il pointe vers https://github.com/jeedom/doc-howto/blob/master/doc/fr_FR/jeelink.migration.asciidoc au lieu de https://github.com/jeedom/documentation/blob/master/howto/fr_FR/jeelink.migration.asciidoc 

Merci

**Comment by zoic21** [comment]
Ca sera corrigé dans la prochaine version stable du plugin. merci du retour
