### ISSUE TITLE
Installation Debian

### ISSUE THREAD

**Issue by dugwood** [jeedom/documentation#186]
Bonjour,

Avant d'installer sur ma Debian, j'ai regardé votre script d'installation, et ça fait plutôt peur :
https://raw.githubusercontent.com/jeedom/core/stable/install/install.sh

1) il s'agit de Debian Stretch et non Strecht
2) votre script demande illico les droits root, au lieu de faire du sudo quand c'est nécessaire
3) vous faites un dist-upgrade avec option `-y`
4) vous cassez les configurations de tout ce qui peut déjà exister : MySQL, Apache, PHP, et je ne parle même pas des cas où Apache va supprimer Nginx ou Lighttpd
5) accessoirement beaucoup d'outils dépendent d'Apache/MySQL sur Debian

**Ce script est dangereux**, et la moindre des choses serait d'indiquer : à n'installer que sur une Debian exclusivement dédiée à l'utilisation de Jeedom, tout le reste sera certainement compromis.

Toute autre utilisation (comme l'installer pour tester sur sa machine personnelle) est vraiment risquée... et totalement contraire à l'esprit Debian.

(et sinon sur un Synology sans Docker, bah... pas d'option, snif...)

**Comment by sarakha63** [comment]
Alors tu as bien fait de regarder le script avant d'installer.

Mais tu aurais du te renseigner un peu plus sur jeedom. Lire la Doc , parcourir le forum etccc.

Tu y verras qu'on incite les gens à avoir une machine exclusive. C'est de la domotique pas un jouet.

Et si kkun veut passer outre ben il peut il a qu'à mettre les mains dans le cambouie... Bon courage

**Comment by lunarok** [comment]
Ce script est là pour une install auto, Si tu as déjà de l'existant il suffit de s'adapter et alors le passage par un script n'est pas nécessaire

**Comment by dugwood** [comment]
Me voilà rassuré... non, mais vraiment, c'est votre réponse ?

Alors je vous la refais dans l'ordre :
- j'ai lu les «tutos» ou les forums
- je me dis, ouah, top, je vais me tenter une install :
- https://www.jeedom.com/site/fr/soft.html => DIY (yeah!)
- qui renvoie sur : https://github.com/jeedom/documentation/tree/master/installation/fr_FR sans plus de pré-requis

Après vu que ça ne fonctionne pas sur mon NAS Synology (parce que Docker pas dispo pour ma version de NAS), je me suis dit que j'allais tenter de faire du Debian Chroot (paquet SynoCommunity), et pour l'instant ça peut fonctionner.

Donc je repars de l'install :
https://github.com/jeedom/documentation/blob/master/installation/fr_FR/other.asciidoc

> Si vous ne maitriser pas un minimum les environnements Linux, nous vous conseillons de partir sur une image officielle (OVF)

Où est-ce qu'il est dit que c'est risqué de le faire sur une Debian «propre» ?

Mais je suis désolé : quelqu'un qui tente ça sur sa Debian (et qui n'a pas pris le temps de lire le fichier install.sh), il se prend une grosse claque (= limite il peut se la réinstaller).

Du coup j'ai peur d'installer votre code PHP s'il est aussi bien écrit... Autant je participe régulièrement à des correctifs (PHP/JS) sur github, là j'avoue que j'ai pris 2 claques...

Donc je regrette, mais votre doc est dangereuse, ce ticket doit rester ouvert tant que ça n'est pas indiqué clairement. Je ne suis pas un «noob», mais si l'envie me prend d'installer Jeedom pour «tester» parce que ça a l'air fun et que de «loin» je crois comprendre Debian, alors je ne devrais pas me prendre une claque de la sorte.

Surtout qu'avec Debian, vous ne devriez même pas utiliser un tel script : vous devriez mettre une liste de paquets à installer, et ensuite fournir les modules pour Apache etc... C'est ça qu'il devrait faire le script, juste l'essentiel, et pas le superflu. Je l'aurai bien fait, mais là bizarrement j'ai plus envie... et oui, je sais, j'ai été méchant dans mon premier message, parce que désolé, ça fait peur.

**Comment by dugwood** [comment]
Et accessoirement c'est en lisant le site de @lunarok que je me suis acheté des ampoules Xiaomi et que j'allais m'installer Jeedom derrière (et que paf, pas de paquet Docker sur mon NAS, tout ça).

D'ailleurs au début j'allais faire une PR, mais vu qu'il y en a plein en attente... bah j'ouvre un ticket avant de commencer à corriger quelque chose. D'ailleurs j'ai bien fait, le ticket est fermé, c'est donc «pas un vrai problème»... Snif.

**Comment by zoic21** [comment]
J'ai rajouté une note sur la doc d'installation https://github.com/jeedom/documentation/blob/master/installation/fr_FR/other.asciidoc
