### ISSUE TITLE
Any plans on adding support for Oregon Scientific BLE?

### ISSUE THREAD

**Issue by libussa** [jeedom/documentation#198]
Some Oregon scientific weather station and thermometers use BLE to send data to an app (android/iphone), and are using the popular (and cheap) th132n and others.
It would be awesome if jeedom could read the data from those stations, as an alternative to buying an RFXcom.

**Comment by libussa** [comment]
Wrong place

**Comment by zoic21** [comment]
This IS notre issue repo, this IS documentation repo.

**Comment by zoic21** [comment]
This IS notre issue repo, this IS documentation repo.
