### ISSUE TITLE
Can't create database

### ISSUE THREAD

**Issue by djo074** [jeedom/documentation#230]
Dear all, 

I tried to install following your tutorial.
When I launch jeedom from web interface, I have this message:
Unable to connect to database
SQLSTATE[HY000]: General error: 1006 Can't create database 'jeedom' (errno: 15245984)''

Thanks a lot for your answers.

Regards,

Djo

![jeedom_installation](https://user-images.githubusercontent.com/23361246/35119773-4842f22e-fc96-11e7-926d-0960f967d018.jpg)

**Comment by zoic21** [comment]
Hello,
This is repo documentation please open an issue fromage market or on forum.
